### ISSUE TITLE
Mid Plate missing in CAD

### ISSUE THREAD

**Issue by ghost** [intositeme/kami-mini#1]
Hello, 

Thank you for sharing!
Is it possible to have the mid plate in the CAD file please? 

<img width="1511" alt="Screen Shot 2022-04-11 at 16 48 47" src="https://user-images.githubusercontent.com/71479641/162765893-b8ac2325-7933-4171-a0db-d7d7e0ed8e0c.png">

**Comment by jeralm** [comment]
I'm also interested

**Comment by issic** [comment]
Yep the same

**Comment by intositeme** [comment]
Sorry, didn't realised it was missing from the CAD when i exported it from Fusion. Haven't been watching this and am not active on Discord.

Merged @cuiviemen updates which mentions the mid plate. Haven't checked the files though.

**Comment by cuiviemen** [comment]
Yep my PR #2 does contain in step file the retraced (from stl) mid plate.
